name: auto-merge

on:
  pull_request:
    types:
    - opened
    - reopened

permissions: read-all

jobs:
  auto-merge:
    permissions:
      pull-requests: write
    uses: boldlink/terraform-module-support/.github/workflows/auto-merge.yaml@main
    secrets:
      AUTOMATION_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
      SLACK_WEBHOOK : ${{secrets.SLACK_WEBHOOK}}
