name: Checkov
on:
  push:
    branches:
      - '!main'
      - 'fix/*'
      - 'fixes/*'
      - 'feat*/*'
      - 'hotfix/*'
      - 'hotfixes/*'
      - 'release/*'
      - 'releases/*'
      - 'chore/*'
      - 'chores/*'
  schedule:
    - cron: "00 18 * * *"

permissions: read-all

jobs:
  checkov-scan:
    uses: boldlink/terraform-module-support/.github/workflows/checkov.yaml@main
    secrets:
      SLACK_WEBHOOK : ${{secrets.SLACK_WEBHOOK}}
