name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    uses: boldlink/terraform-module-support/.github/workflows/release.yaml@1.0.0
    with:
      config-name:  workflows/config/rd-config.yaml
    secrets:
      AUTOMATION_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
      SLACK_WEBHOOK : ${{secrets.SLACK_WEBHOOK}}
