name: Release

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    uses: boldlink/terraform-module-support/.github/workflows/release.yaml@main
    with:
      config-name:  workflows/config/rd-config.yaml
    secrets:
      AUTOMATION_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
      SLACK_WEBHOOK : ${{secrets.SLACK_WEBHOOK}}
